### ISSUE TITLE
Bug report for transfer learning.

### ISSUE THREAD

**Issue by ha-lins** [Shen-Lab/GraphCL#13]
Hi @yyou1996,

Thanks for your efforts in this project. 

The bug has been fixed, which is due to the pyG's inconsistent with the specified version (1.0.3). The author has mentioned it [here](https://github.com/snap-stanford/pretrain-gnns/issues/14).

**Comment by YEARNLL** [comment]
Two things for this bug in **transferLearning_MoleculeNet_PPI\bio** may help (maybe similar in chem):
- replace `cat_dim` to `__cat_dim__` in `loader.py` line177
- replace` return self.propagate(self.aggr, edge_index, x=x, edge_attr=edge_embeddings)` in `model.py` line52 with `return self.propagate(edge_index[0], x=x, edge_attr=edge_embeddings)` and replace line111 with `return self.propagate(edge_index[0], x=x, edge_attr=edge_embeddings, norm = norm)`
