### ISSUE TITLE
How to speed up the pretraining on chem in Transferlearning experiment?

### ISSUE THREAD

**Issue by ha-lins** [Shen-Lab/GraphCL#25]
Hi @yyou1996,

I wonder how to speed up the pretraining on chem data. How long did you use to pretrain one epoch on it? Which gpu version did you use? I think the speed bottleneck is the CPU or io. I tried increasing the `num_workers` while it seems no effects.

**Comment by check-777** [comment]
I run the pretraining on 3090,and the number_works = 8.Besides,I didn't change the source code.

**Comment by ha-lins** [comment]
@check-777 Thanks for your helpful comments. Could you pls share the package version of `pyG` and `pytorch`? 3090 merely supports `cuda 11.1`. Higher version of `PyG` might leads to some inconsistent results with those in the paper.

**Comment by check-777** [comment]
> @check-777 Thanks for your helpful comments. Could you pls share the package version of `pyG` and `pytorch`? 3090 merely supports `cuda 11.1`. Higher version of `PyG` might leads to some inconsistent results with those in the paper as mentioned in README.md.
That's true.And I fixed some bugs that casued by the ptG version.You can check out this url https://github.com/snap-stanford/pretrain-gnns/issues/14#issuecomment-647493335
That's my versions about pyG and pytorch:
pytorch1.7.1
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
pip install torch-geometric

**Comment by ha-lins** [comment]
@check-777 Thanks for your help. I wonder if this problem is fixed and reproduce the pretraining performance successfully. Are the downstream performance close to the paper results for the latest version of pyG? Hope to chat more about this via WeChat (ls825521138).
