### ISSUE TITLE
I can't reproduce the published results of unsupervised_Cora_Citeseer

### ISSUE THREAD

**Issue by c747903646** [Shen-Lab/GraphCL#34]
I have respectively run the codes using commands `python -u execute.py --dataset citeseer --aug_type node --drop_percent 0.20 --seed 39 --save_name cite_best_dgi.pkl --gpu 0`  and  `python -u execute.py --dataset cora --aug_type node --drop_percent 0.20 --seed 39 --save_name cite_best_dgi.pkl --gpu 0` on the following two environments:

 1. soft env: `CUDA 11.1, Python 3.6.7, PyTorch 1.8.0`, hard env: `RTX 3080 laptop`
 2. soft env: `CUDA 10.0, Python 3.7.6, Pytorch 1.3.1`, hard env: `RTX 2080ti `

and respectively got the results as the following:

1.

**Citeseer**
```
Average accuracy:[0.7279]
Mean:[72.7880]
Std :[0.1394]
```

**Cora** 
```
Average accuracy:[0.8124]
Mean:[81.2360]
Std :[0.1274] 
```

2.

**Citeseer**
```
Average accuracy:[0.7256]
Mean:[72.5620]
Std :[0.1615]
```

**Cora** 
```
Average accuracy:[0.8137]
Mean:[81.3660]
Std :[0.1649]
```

But according to the paper's Appendix G, the results should be 73.14±0.15 on Citeseer and 81.76±0.17 on Cora. How can I reproduce the results?

**Comment by yyou1996** [comment]
Hi @c747903646, thanks for asking.

@yongduosui any comments?
