### ISSUE TITLE
Question about the unsupervised_TU gsimclr.py

### ISSUE THREAD

**Issue by scottshufe** [Shen-Lab/GraphCL#40]
Hi GraphCL team, thanks for your excellent work.

I have some questions about the loss function in unsupervised_TU/gsimclr.py:
in your article eq.(3), you claim that the positive pairs and negative pairs are composed of augmentations, but in the code I find that you use the original sample and one augmentation to form a positive pair. I don't understand the differences between these two methods and wish you could give me some suggestions or explanation. Thank you in advance.

**Comment by yyou1996** [comment]
Hi @scottshufe,

Sorry for the late reply. Double augmentations are implemented for experiments except unsupervised_TU due to some implementation issue then (e.g. please refer to https://github.com/Shen-Lab/GraphCL/tree/master/semisupervised_TU).

**Comment by scottshufe** [comment]
Hi, Mr. You. Thanks for your reply. I think I have implemented the code of double augmentations, but I need to figure out the differences between single augmentation and double augmentations...If you have any ideas on this question, I would love to hear your opinion :smile:

**Comment by CynthiaLaura6gf** [comment]
Thanks for your excellent codes, I have some problems with the loss function. what's the difference between the loss function in the class simclr and the loss function in the class of GcnInfomax.

**Comment by scottshufe** [comment]
> Thanks for your excellent codes, I have some problems with the loss function. what's the difference between the loss function in the class simclr and the loss function in the class of GcnInfomax.

I think the loss in GcnInfomax is the same as _DGI (2019 ICLR)_ which generalizes DeepInfomax (2019 ICLR) from images to graphs. It aims to maximize the mutual information between local patches and the global graph. And GraphCL (or simclr) aims to maximize the mutual information between the augmentations.

**Comment by yyou1996** [comment]
@scottshufe I feel in small datasets it differs little, while things might change in large-scale datasets. The positive or negative influence depends on whether the augmentation is rational for the downstream.

**Comment by scottshufe** [comment]
Got it. Thanks again, Mr. You. Maybe I should read more GCL articles and run some experiments to better understand these questions.
