### ISSUE TITLE
Positive pairs in data augmentaions.

### ISSUE THREAD

**Issue by Bunnyqiqi** [Shen-Lab/GraphCL#43]
For GraphCL paper,  the positive pairs are both augmentations views using some augmentations in GraphCL paper. 
But when I read code in unsupervised_TU/gsimclr.py, I found only one view is augmented, the other view is original without augmentation. 
I wonder if I'd like to reproduct the results in paper, should I change x to another augmentaion view using some augmentations? 
In other words, such implementations in code means one original view and one augmentaion view is enough for experiement?
![image](https://user-images.githubusercontent.com/53176096/159112783-c778fd78-742f-41d7-8960-f3db474cf12e.png)

Besides, In GraphCL_Automated/unsupervised/gsimclr.py, I have similar questions. In code , there is only compute one augmentation view's distribution, and the other view is original view. I think there are some differences between paper and code. Could you help me explain such cases?

By the way, I'm so thankful to all of you for such great and inspirable work! Best wishes for you !

**Comment by yyou1996** [comment]
Hi @Bunnyqiqi,

Sorry for the late reply. Please refer to https://github.com/Shen-Lab/GraphCL/issues/40.
