### ISSUE TITLE
论文报告结果

### ISSUE THREAD

**Issue by Bunnyqiqi** [Shen-Lab/GraphCL#47]
另外，论文中报告的结果是五次实验的平均值，请问这五次实验具体改变的参数是什么呢？是否是改变在evaluate embedding.py里面的svc_classify的random state值，得到五次实验结果取平均呢？如下图所示
![image](https://user-images.githubusercontent.com/53176096/165896371-d9473ab5-4eb8-4fec-9919-4d86b0ffa15f.png)

**Comment by yyou1996** [comment]
Hi @Bunnyqiqi,

I think you can directly run 5 times to get 5 runs with different initializations for pre-training.
